Parte 2/Flores/Flores/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('app/img/favicon.ico'))),
    path('', include('pwa.urls')),
]

admin.site.site_title = "Tienda de flores"
admin.site.site_header = "Administración de la tienda"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Parte 2/Flores/app/urls.py
from django.db import router
from django.urls import path, include
from .views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('suscripcion', SuscripcionViewSet)

urlpatterns = [
    path('', index, name="index"),
    path('about/', about, name="about"),
    path('login/', login, name="login"),
    path('productos/', productos, name="productos"),
    path('lista_productos/', lista_productos, name="lista_productos"),    
    path('agregar/', agregar, name="agregar"),
    path('modificar/<id>/', modificar, name="modificar"),
    path('eliminar/<id>/', eliminar, name="eliminar"),
    path('registro_usuario/', registro_usuario, name="registro_usuario"),
    path('suscripcion/', suscripcion_usuario, name="suscripcion"),
    path('lista_suscripcion/', lista_suscripcion, name="lista_suscripcion"),
    path('eliminar_suscriptor/<id>/', eliminar_suscriptor, name="eliminar_suscriptor"),
    path('eliminar_descuento/<id>/', eliminar_descuento, name="eliminar_descuento"),
    path('modificar_suscripcion/<id>/', modificar_suscripcion, name="modificar_suscripcion"),
    path('agregar_descuento/', agregar_descuento, name="agregar_descuento"),
    path('descuentos/', descuentos, name="descuentos"),
    path('api/', include(router.urls)),
    path('carrito/', carrito, name="carrito")
]

Parte 2/Flores/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField, EmailField, IntegerField
from django.db.models.fields.related import ForeignKey

# Create your models here.
class tipo_producto(models.Model):
    tipo = models.CharField(max_length=80)
    
    def __str__(self):
        return self.tipo
        
class producto(models.Model):
    nombre = models.CharField(max_length=100)
    precio = models.IntegerField()
    tipo = models.ForeignKey(tipo_producto, on_delete=models.CASCADE)
    imagen = models.ImageField(null=True, blank=True)
    
    
    def __str__(self):
        return self.nombre
    
class suscripcion(models.Model):
    descripcion = CharField(max_length=200)
    descuento = IntegerField()
    duracion = IntegerField()
    
    def __str__(self):
        return self.descripcion

class suscriptUser(models.Model):
    usuario = CharField(max_length=200)
    email = EmailField(max_length=200)
    descripcion = ForeignKey(suscripcion, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.usuario

#python manage.py makemigrations --> CREA ARCHIVO MIGRATIONS
#python manage.py migrate --> ENVIA EL ARCHIVO A LA BD
#python manage.py createsuperuser --> CREA EL ADMIN DE LA WEB

Parte 2/Flores/app/templates/app/about.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}
    <div class="form">
        <form action="action_page.php">
            <img src="{% static 'app/img/llave-inglesa.jpg' %}" alt="" height="100px" width="100px">
            <h1 class="textbig">Contáctese con el JC</h1>
            <h3 class="textlow">Ingrese sus datos y su mensaje</h3>

          <label for="name">Su nombre:</label>
          <input type="text" id="name" name="about" placeholder="Escriba aquí su nombre...">
      
          <label for="email">Su correo eléctronico:</label>
          <input type="text" id="email" name="about" placeholder="Escriba aquí su correo eléctronico...">
      
          <label for="duda">Categoría de producto sobre el que tiene la duda:</label>
          <select id="duda" name="duda">
            <option value="maceteros">Maceteros</option>
            <option value="tierrahojas">Tierra de hojas</option>
            <option value="arbustos">Arbustos</option>
            <option value="flores">Flores</option>
            <option value="Cuenta">Cuenta de socio</option>
            <option value="otro">Otro</option>
          </select>
      
          <label for="subject">Tu duda o consulta:</label>
          <textarea id="subject" name="subject" placeholder="Cuéntanos en qué te podemos ayudar..." style="height:200px"></textarea>
      
          <input type="submit" value="Guardar y enviar">
      
        </form>
      </div>
{% endblock  %}

Parte 2/Flores/app/templates/app/agregar.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}
<div class="addProduct">

    <div class="formulario">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <table>
                {{ form|crispy }}
            
            <div class="buttons" style="border-top-style: solid;border-top-width: 0px;margin-top: 50px;">   
                <input type="submit" value="Guardar"  class="btn-guardar">
                <input type="reset" value="Limpiar" class="btn-limpiar"> 
            </div>
            </table>
        </form>
        {{ mensaje }}
    </div>

</div>

{% endblock %}

Parte 2/Flores/app/templates/app/agregar_descuento.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}

<div class="addProduct">

    <div class="formulario">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <table>
                {{ formu|crispy }}
            
            <div class="buttons" style="border-top-style: solid;border-top-width: 0px;margin-top: 50px;">   
                <input type="submit" value="Guardar"  class="btn-guardar">
                <input type="reset" value="Limpiar" class="btn-limpiar"> 
            </div>
            </table>
        </form>
        {{ mensaje }}
    </div>

</div>

{% endblock %}

Parte 2/Flores/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {%load static%}
  <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
  <title>Jardín Comunitario JC</title>

  {% load pwa %}

  {% progressive_web_app_meta %}

</head>
<body>
  <!--Logo_Busqueda_Nav-->
  <div class="contenedor">
    <header>
      <div class="logo_principal">
        <a href="{% url 'index'%}"><img src="{% static 'app/img/1eda7a920595361944650b58376e27ec-flor-roja-rosa-plana-by-vexels.png' %}" alt="" height="60px"></a> 
      </div>
      <div>
        <!--<input type="text" name="search" placeholder="Busca algún producto...">-->
      </div>
      <nav>
        <li>
          <a href="{% url 'productos'%}" class="producto-btn"><i class="fas fa-shopping-basket"></i></a>
        </li>
        <li>
          <a href="{% url 'about' %}" class="contacto-btn"><i class="fas fa-phone"></i></a>
        </li>
        
        {% if perms.app.delete_user %}
          <li>
            <a href="{% url 'lista_productos' %}" class="inventario-btn"><i class="fas fa-boxes"></i></a>
          </li>
          <li>
            <a href="{% url 'lista_suscripcion' %}" class="inventario-btn"><i class="fas fa-users"></i></a>
          </li>
          <li>
            <a href="{% url 'descuentos' %}" class="inventario-btn"><i class="fas fa-percent"></i></a>
          </li>
        {% endif %}

        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}" class="socio-btn" id="logout-btn"><i class="fas fa-sign-out-alt"></i> {{user.first_name}}</a>
        </li>
        <li>
          <a href="{% url 'suscripcion' %}" class="socio-btn" id="logout-btn">Suscripción</a>
        </li>
        <li>
          <a href="{% url 'carrito' %}" class="socio-btn" id="logout-btn" ><i class="fas fa-shopping-cart"></i></a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'login' %}" class="socio-btn"><i class="fas fa-sign-in-alt"></i></a>
        </li>
        {% endif %}
        <div class="animation start-home"></div>
      </nav>
    </header>
  </div>

{%block contenido%}


{% endblock %}


  <!--Footer-->
  <footer class="footer">
    <p>Jardín Comunitario © <a href="https://youtu.be/dQw4w9WgXcQ" target="_blank" rel="noopener noreferrer">Dream Team</a> 2021</p>
  </footer>

  <script src="{% static 'app/js/jquery-3.2.1.js' %}"></script>
  <script src="{% static 'app/js/javascript.js' %}"></script>
  <script src="https://kit.fontawesome.com/2ffca1f776.js" crossorigin="anonymous"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script src="{% static 'app/js/sweetAlert2.js' %}"></script>
</body>
</html>

Parte 2/Flores/app/templates/app/carrito.html
{% extends 'app/base.html' %}
{% load static %}


{% block contenido %}
    <a class="btn-agregarProducto" href="https://youtu.be/GJDNkVDGM_s">Proceder al pago...?</a>

    <div class="placeholder">
        <li>
            <h1 id="placeholder_cart">Aquí aparecerían los productos que agregues al carrito de compras...</h1>
        </li>
    </div>   
    
    <div>
        {% include 'app/paginator.html' %}
    </div>
{% endblock %}

Parte 2/Flores/app/templates/app/descuentos.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}
    <a class="btn-agregarProducto" href="{% url 'agregar_descuento' %}">Agregar</a>
    <div id="titulo-lista">
        <h1>Suscripciones y descuentos</h1>
    </div>
    <div class="contenido-lista">
        <table>
            <thead>
                <tr>
                    <th>TIPO DESCUENTO</th>
                    <th>DESCUENTO</th>
                    <th>DURACION</th>
                    <th>OPCIONES</th>
                </tr>
            </thead>
            <tbody>
                {% for aux in listaSuscripcion %}
                <tr>
                    <td> {{aux.descripcion}} </td>
                    <td> {{aux.descuento}} </td>
                    <td> {{aux.duracion}} </td>
                    <td>
                        <a class="btn-eliminarLista" href="{% url 'eliminar_descuento' aux.id %}" >Eliminar</a>
                        <a class="btn-modificarLista" href="{% url 'modificar_suscripcion' aux.id %}">Modificar</a>
                    </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

Parte 2/Flores/app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}



{% block contenido %}

    <!--slideshow-->
    <section class="banner">
      <div class="slider">        
        <ul>
          <li><img src="{% static 'app/img/flores-1.jpg' %}" alt=""></li>
          <li><img src="{% static 'app/img/maceteros-1.jpg' %}" alt=""></li>
          <li><img src="{% static 'app/img/flores-2.jpg' %}" alt=""></li>
          <li><img src="{% static 'app/img/maceteros-2.jpg' %}" alt=""></li>
          <li><img src="{% static 'app/img/flores-3.jpg' %}" alt=""></li>
        </ul>
      </div>
    </section>
    <!--Tipo de productos-->
    <div class="wrap">
      <h1>Productos destacados</h1>
        <section class="products-list">
          <div class="product-item" category="tierra_hojas">
            <img src="{% static 'app/img/tierra_hoja-cat.jpg' %}" alt="">
            <a href="#">Tierra de hojas Prosan</a>
          </div>
          <div class="product-item" category="tierra_hojas">
            <img src="{% static 'app/img/tierra_hoja-cat-2.jpg' %}" alt="">
            <a href="#">Tierra de hojas Anasac</a>
          </div>
          <div class="product-item" category="flores">
            <img src="{% static 'app/img/flor-cat.jpg' %}" alt="">
            <a href="#">Liliums</a>
          </div>
          <div class="product-item" category="flores">
            <img src="{% static 'app/img/flor-cat-2.jpg' %}" alt="">
            <a href="#">Rosas</a>
          </div>
          <div class="product-item" category="maceteros">
            <img src="{% static 'app/img/macetero-cat-1.jpg' %}" alt="">
            <a href="#">Maceteros de yeso</a>
          </div>
          <div class="product-item" category="maceteros">
            <img src="{% static 'app/img/macetero-cat-2.jpg' %}" alt="">
            <a href="#">Maceteros de plástico</a>
          </div>
          <div class="product-item" category="arbustos">
            <img src="{% static 'app/img/arbusto-cat.jpg' %}" alt="">
            <a href="#">Arbusto artificial</a>
          </div>
          <div class="product-item" category="arbustos">
            <img src="{% static 'app/img/arbusto-cat-2.jpg' %}" alt="">
            <a href="#">Arbusto natural</a>
          </div>
        </section>
    </div>

{% endblock  %}

Parte 2/Flores/app/templates/app/lista_productos.html
{% extends 'app/base.html' %}
{% load static %}


{% block contenido %}
{% if user.is_authenticated %}
    {% if perms.app.add_producto %}
    <a class="btn-agregarProducto" onclick="confirmarAgregar( {{ aux.id }} )">Agregar Producto</a>
    {% endif %}

    {% if perms.app.delete_user %}
    <div class="listas">
        {% for aux in lista %}
        <div class="product">
            <h3 class="nombre-producto">{{aux.nombre}}</h3>
            {% if aux.imagen %}
                <img src="{{ aux.imagen.url }}" alt="" height="300px" width="300px">
            {% else %}
                <img src="{% static 'app/img/no-hay-imagen.jpg' %}" alt="" height="300px" width="300px">
            {% endif %}
        <div class="botones">
            {% if perms.app.change_producto %}
            <a class="modify" onclick="confirmarModificar( {{ aux.id }} )">Modificar</a>
            {% endif %}
            {% if perms.app.delete_producto %}
            <a class="delete" onclick="confirmarEliminar( {{ aux.id }} )">Eliminar</a>
            {% endif %}
        </div>    

        </div>
        {% endfor %}
    </div>
    
    <div>
        {% include 'app/paginator.html' %}
    </div>
    {% else %}
    <div class="peppo-logo">
        <img src="{% static 'app/img/peppo.png' %}" alt="" class="icono-peppo">
        <div>
            <a href="https://www.youtube.com/watch?v=YsLCjOl0Bfw" class="btn-agregarProducto">ACCESO DENEGADO</a>
        </div>
        
        
    </div>
    {% endif %}
{% endif %}
{% endblock %}

Parte 2/Flores/app/templates/app/lista_suscripcion.html
{% extends 'app/base.html' %}
{% load static %}


{% block contenido %}
    <div id="titulo-lista">
        <h1>Suscripciones de usuarios</h1>
    </div>
    <div class="contenido-lista">
        <table>
            <thead>
                <tr>
                    <th>SUSCRIPCIÓN</th>
                    <th>USUARIO</th>
                    <th>CORREO</th>
                    <th>¿Deseas eliminar?</th>
                </tr>
            </thead>
            <tbody>
                {% for aux in listaUsuarios %}
                <tr>
                    <td> {{aux.descripcion}} </td>
                    <td> {{aux.usuario}} </td>
                    <td> {{aux.email}} </td>
                    <td><a class="btn-eliminarLista" href="{% url 'eliminar_suscriptor' aux.id %}" >Eliminar</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

Parte 2/Flores/app/templates/app/modificar.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}
<div class="addProduct">

    <div class="formulario">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form|crispy }}
            <div class="buttons" style="border-top-style: solid;border-top-width: 0px;margin-top: 50px;">   
                <input type="submit" value="Modificar" class="btn-guardar">
                <input type="reset" value="Limpiar" class="btn-limpiar"> 
            </div>
            </table>
        </form>
        {{ mensaje }}
    </div>
</div>

{% endblock %}

Parte 2/Flores/app/templates/app/modificar_suscripcion.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

<div class="addProduct">

    <div class="formulario">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <table>
                {{ formu|crispy }}
            
            <div class="buttons" style="border-top-style: solid;border-top-width: 0px;margin-top: 50px;">   
                <input type="submit" value="modificar"  class="btn-guardar">
                <input type="reset" value="Limpiar" class="btn-limpiar"> 
            </div>
            </table>
        </form>
        {{ mensaje }}
    </div>

</div>

{% endblock %}

Parte 2/Flores/app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="contenedor-paginator">
    <ul class="pagination">
        {% if lista.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ lista.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}

        {% for page in paginator.page_range %}
            {% if forloop.last and page != lista.number and paginator.num_pages > 7 %} 
                {% if lista.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ lista.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}

            {% if page == lista.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}

            {% if page < 7 or page == lista.number %}
            <li class="page-item {% if page == lista.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}

        {% if lista.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ lista.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>



{% endif %}

Parte 2/Flores/app/templates/app/productos.html
{% extends 'app/base.html' %}
{% load static %}


{% block contenido %}
<div class="page-content">
    {% for aux in lista %}
    <div class="product">
        <h3 class="nombre-producto">{{aux.nombre}}</h3>
        {% if aux.imagen %}
            <img src="{{ aux.imagen.url }}" alt="" height="300px" width="300px">
        {% else %}
            <img src="{% static 'app/img/no-hay-imagen.jpg' %}" alt="" height="300px" width="300px">
        {% endif %}
        <div class="precio">
            <h3>${{aux.precio}} </h3>
        </div>
        <a href="#"><i class="fas fa-cart-plus"></i><span>Agregar</span></a>
    </div>
    {% endfor %}

</div>
<div>
    {% include 'app/paginator.html' %}
</div>
{% endblock %}

Parte 2/Flores/app/templates/app/suscripcion.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}
<div class="addProduct">

    <div class="form-sus">
        <h1>¡Suscríbete!</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <table>
                {{ formulario|crispy }}
            
            <div class="buttons" style="border-top-style: solid;border-top-width: 0px;margin-top: 50px;">   
                <input type="submit" value="Guardar"  class="btn-guardar">
            </div>
            </table>
        </form>
        {{ mensaje }}
    </div>

</div>
{% endblock %}